[package]
name = "swapchain"
version = "0.1.0"
authors = ["tellnnn <tellurium3262@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
