[package]
name = "model"
version = "0.1.0"
authors = ["tellnnn <tellurium3262@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
cgmath = "0.18"
env_logger = "0.8"
futures = "0.3"
image = "0.23"
log = "0.4"
tobj = "3.0"
wgpu = { version = "0.8", features = ["cross"] }
winit = "0.24"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[[bin]]
name = "main"
path = "src/main.rs"